//useEffect: para carregar na pagina
//useState: para salvar requisição em variavel
import React, { useEffect, useState } from "react";
import api from "../src/API/api";

import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';

//indormando ao ts a tipagem dos dados
interface ResponseData {
  id: string;
  name: string;
  description: string;
  thumbnail:{
    path: string;
    extencion: string;
  };
}

//requisição
const Comics: React.FC = () => {

  const [comics, setComics] = useState<ResponseData[]>([]);

  useEffect(() => { //executa sempre que a pagina eh carregada
     api
     .get('/comics')
     .then(response => {
       setComics(response.data.data.results);
     })
     .catch(err => console.log(err));
}, []);

return (
  <html>
    <div className={styles.container}>
      <Head>
        <title>MARVEL BRISANET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          MARVEL BRISANET TEST
        </h1>

        <p className={styles.description}>
          descrição
        </p>

        <div className={styles.grid}>
          <a href="link heroi" className={styles.card}>
            <h2>Heroi</h2>
            <p>descrção</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
          Desenvolvido por Denilson Oliveira
      </footer>
    </div>
  </html>
)

}

export default Comics;